package com.fa26se040.icss.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ConfigKey {

    ACCESS_REQUEST_MAX_GROUP_MEMBERS("ACCESS_REQUEST_MAX_GROUP_MEMBERS", "30"),
    ACCESS_REQUEST_MAX_DURATION_HOURS("ACCESS_REQUEST_MAX_DURATION_HOURS", "12"),
    ACCESS_REQUEST_MAX_ADVANCE_DAYS("ACCESS_REQUEST_MAX_ADVANCE_DAYS", "30"),
    ACCESS_REQUEST_PAST_START_BUFFER_MINUTES("ACCESS_REQUEST_PAST_START_BUFFER_MINUTES", "5"),
    ACCESS_REQUEST_GROUP_ALLOWED_IN_PRIVATE("ACCESS_REQUEST_GROUP_ALLOWED_IN_PRIVATE", "false"),
    NOTIFICATION_PENDING_OVERDUE_HOURS("NOTIFICATION_PENDING_OVERDUE_HOURS", "24"),
    NOTIFICATION_EXPIRING_SOON_LEAD_MINUTES("NOTIFICATION_EXPIRING_SOON_LEAD_MINUTES", "30"),
    SECURITY_MEMBER_LOOKUP_RATE_PER_MINUTE("SECURITY_MEMBER_LOOKUP_RATE_PER_MINUTE", "20");

    private final String key;
    private final String defaultValue;
}
