package com.fa26se040.icss.enums;

public enum NotificationType {
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    EXPIRING_SOON,
    ACCESS_DENIED,
    ADDED_TO_GROUP,
    NEW_REQUEST_PENDING,
    REQUEST_CANCELLED,
    PENDING_OVERDUE,
    EVENT_MODE_LIMIT_CHANGED,
    EVENT_MODE_CHANGED,
    EVENT_MODE_EXPIRING,
    EVENT_MODE_SCHEDULED,
    EVENT_MODE_SCHEDULE_STARTING,
    EVENT_MODE_SCHEDULE_FAILED,
    // Step 5b (BR-TC-10, BR-TC-16) — khung A1, CHECK constraint sẽ bổ sung ở migration V56
    AREA_TYPE_CHANGED,
    REQUEST_SYSTEM_CANCELLED,
    // Khách G-A (BR-GV-33, V60)
    GUEST_VISIT_PENDING,
    GUEST_VISIT_APPROVED,
    GUEST_VISIT_REJECTED,
    GUEST_VISIT_REVOKED,
    GUEST_VISIT_EXPIRED,
    GUEST_PHOTO_REQUIRED
}
