package com.fa26se040.icss.enums;

public enum NotificationType {
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    EXPIRING_SOON,
    ACCESS_DENIED,
    ADDED_TO_GROUP,
    NEW_REQUEST_PENDING,
    REQUEST_CANCELLED,
    PENDING_OVERDUE,
    EVENT_MODE_LIMIT_CHANGED,
    EVENT_MODE_CHANGED,
    EVENT_MODE_EXPIRING,
    EVENT_MODE_SCHEDULED,
    EVENT_MODE_SCHEDULE_STARTING,
    EVENT_MODE_SCHEDULE_FAILED
}
